### ISSUE TITLE
broken image and opera

### ISSUE THREAD

**Issue by jalbertbowden** [Code4HR/previous-landing#104]
there's a broken image in the content and there's a size difference in the main image (ndoch) in opera

**Comment by qwo** [comment]
if this looks correct merge it in, I removed NDOCH link.
http://stanzh.com/c4hrva-landing/

On Sat, Jun 14, 2014 at 8:27 PM, albert notifications@github.com wrote:

> there's a broken image in the content and there's a size difference in the
> main image (ndoch) in opera
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/c4hrva-landing/issues/104.
> 
> ---
> 
> Spam
> https://www.spamtrap.odu.edu/canit/b.php?i=03MeorGgE&m=6201da8fab1b&t=20140614&c=s
> Not spam
> https://www.spamtrap.odu.edu/canit/b.php?i=03MeorGgE&m=6201da8fab1b&t=20140614&c=n
> Forget previous vote
> https://www.spamtrap.odu.edu/canit/b.php?i=03MeorGgE&m=6201da8fab1b&t=20140614&c=f

## 

Stanley Zheng
@stanzheng http://twitter.com/stanzheng

**Comment by jalbertbowden** [comment]
did you even look? at the bottom of the page. the image has no src.

**Comment by qwo** [comment]
I think you mean this line, sorry i thought you meant the ndoch image on the top

**Comment by qwo** [comment]
Looks like it was never added, the git blame shows its always been blank. unless @BretFisher was interested in putting in an actual image i will remove the tag

**Comment by jalbertbowden** [comment]
wow. how did we never notice that

**Comment by qwo** [comment]
Yeah pretty funny, its forked on the original template to other brigades. It looks like @betanyc caught it and removed it out of theres.

https://github.com/c4hrva/c4hrva-landing/blame/gh-pages/index.html#L336

**Comment by jalbertbowden** [comment]
sad state of affairs when not one brigade is validating their docs. oh well. take it out or leave it.
