### ISSUE TITLE
Quick issue that you may be able to spot with my site?

### ISSUE THREAD

**Issue by pzula** [Code4HR/previous-landing#18]
I added blog functionality to the Code for Summit County website, which is based on the Hampton Road jekyll site, and I must have done something weird to it because suddenly my logo no longer shows up. I looked through github (https://github.com/CodeForSummitCounty/codeforsummitcounty.org/tree/gh-pages) and was unable to see why the logo is now showing up in the source code with two // in front of it, instead of none. Do you have a quick minute to take a look at it and let me know if you see anything wrong?

**Comment by jalbertbowden** [comment]
persa: where can i see this? live site?

On Mon, Jun 3, 2013 at 10:02 PM, Persa notifications@github.com wrote:

> I added blog functionality to the Code for Summit County website, which is
> based on the Hampton Road jekyll site, and I must have done something weird
> to it because suddenly my logo no longer shows up. I looked through github (
> https://github.com/CodeForSummitCounty/codeforsummitcounty.org/tree/gh-pages)
> and was unable to see why the logo is now showing up in the source code
> with two // in front of it, instead of none. Do you have a quick minute to
> take a look at it and let me know if you see anything wrong?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/18
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by pzula** [comment]
http://codeforsummitcounty.org

**Comment by jalbertbowden** [comment]
caption logo's url has a bad url: "img src="//images/logo-300x300.png"

that's it, just resolve the url...i edited it in Chrome to the full path and it rendered.

**Comment by pzula** [comment]
I know, but why is Jekyll outputting that? Check the repo I referenced?

**Comment by BretFisher** [comment]
Are you asking us a Jekyll question? Our template doesn't use Jekyll. Maybe ask in a Jekyll IRC or forum?

**Comment by pzula** [comment]
Hmmmm perhaps I'm confused because I forked from Virginia Beach and now you are merged together?

**Comment by BretFisher** [comment]
Virginia Beach = Hampton Roads, we just renamed repo. Your repo above isn't a fork of anything that I can tell. We've never used Jekyll that I know of, but maybe one of our forks has.

**Comment by jalbertbowden** [comment]
@pzula pretty sure it's the "/" in the images url....i'm not familiar with jekyll, but i went to your repo and carousel caption img has "/" in it's path...i then looked at the images in the featurettes and they do not....pretty sure that's it.

**Comment by BretFisher** [comment]
@pzula you're welcome to join us in IRC if you want to talk more, but we've not done Jekyll yet.  http://webchat.freenode.net/?channels=codeforva&uio=d4
