### ISSUE TITLE
create a c4hrva logo!!

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/previous-landing#3]

**Comment by milafrerichs** [comment]
please ignore the previous message, this fixes issue 3 for codeforsandiego

**Comment by qwo** [comment]
Old topic but any suggestions about theming
-Ships
-Mermaids
-Dolphins?
Any particularly patriotic theme or historic events

**Comment by kmcurry** [comment]
https://drive.google.com/file/d/0B_WC8QOgiwjzN1hDdktYNGZTajQ/edit?usp=sharing
