### ISSUE TITLE
Blue link on red background hurts eyes

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/previous-landing#35]
![screen shot 2014-01-08 at 10 24 31 pm](https://f.cloud.github.com/assets/69151/1874873/a355a0da-78dd-11e3-830f-895815643049.png)

**Comment by qwo** [comment]
is the white on red background too hard to read? I was going to suggest a
box border for the text to make all the text easier to read

On Wed, Jan 8, 2014 at 10:25 PM, Kevin Curry notifications@github.comwrote:

> [image: screen shot 2014-01-08 at 10 24 31 pm]https://f.cloud.github.com/assets/69151/1874873/a355a0da-78dd-11e3-830f-895815643049.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/35
> .

## 

Stanley Zheng
B.S. Comp Sci ODU '14
Cell: (347)-399-3732
@stanzheng

**Comment by kmcurry** [comment]
Not having much issue with the white. Just the hyperlink blue.

On Wed, Jan 8, 2014 at 10:28 PM, Stanley Zheng notifications@github.comwrote:

> is the white on red background too hard to read? I was going to suggest a
> box border for the text to make all the text easier to read
> 
> On Wed, Jan 8, 2014 at 10:25 PM, Kevin Curry notifications@github.comwrote:
> 
> > [image: screen shot 2014-01-08 at 10 24 31 pm]<
> > https://f.cloud.github.com/assets/69151/1874873/a355a0da-78dd-11e3-830f-895815643049.png>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/c4hrva/c4hrva-landing/issues/35>
> > .
> 
> ## 
> 
> Stanley Zheng
> B.S. Comp Sci ODU '14
> Cell: (347)-399-3732
> @stanzheng
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/35#issuecomment-31899946
> .

## 

Kevin Curry
Advisor, Civic Hacker
Code for America
http://brigade.codeforamerica.org

Let's CodeAcross together this February 21-23:
http://www.codeforamerica.org/codeacross

**Comment by qwo** [comment]
fixed

387c9af
