### ISSUE TITLE
Link challenges to details

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/previous-landing#39]
Make the thumbnails and some words in the copy hyperlinks to details. 

Need place to link first.

I'm not sure where/how we should curate details. Currently there are individual slide decks here in our [CodeAcross 2014 G-Drive](https://drive.google.com/folderview?id=0B_WC8QOgiwjzbkx1b1g4Unh6bzQ&usp=sharing). We could also use HRVAwiki. Whatever we choose we need the ability to enable wide curation, i.e., updating HTML in Github for web pages does not scale.

**Comment by BretFisher** [comment]
+1 for hrvawiki. would allow for participation before event (everyone can
add-to, not just brigade team members), would heighten the existence of
hrvawiki...

**Comment by kmcurry** [comment]
We need also the ability to present them in front of groups, I think. Does HRVAwiki mean we'll need to manage two things (curate in HRVAwiki and copy/edit for slides)?

Any negative impact to the vibe/community of HRVAwiki if it surges with projects and project teams?

The slide deck can be opened up more. It can even be public/anyone with link edit if we want.

Not advocating for deck, just elaborating on circumstances.

Also, didn't mean to rule out Github as a source for details, just requirement for coding to contribute. Github has wikis too. I don't know that we'll want to create a repo to curate a challenge. We could create a /challenges repo like /tasks and use issues + wiki. Similar to getting project people into HRVAwiki using Github could get non-coders and gov into using Github, which is good, too.

**Comment by qwo** [comment]
I would suggest a hackpad/hrvawiki solution.

We could create a CodeAcross Parent, and list out all the challenges/activities as pages under that. 
I believe after a point the slide decks will be a goto pitch and most collaboration will occur on the wiki/hackpad.

**Comment by kmcurry** [comment]
Need to clarify: Purpose is not to set up a space for future collab. We'll
let the teams decide what they want, which will almost certainly be Github.
The purpose here is to provide further description about each challenge
beyond the one liner. That is all.

On Saturday, January 11, 2014, Stanley Zheng wrote:

> I would suggest a hackpad/hrvawiki solution.
> 
> We could create a CodeAcross Parent, and list out all the
> challenges/activities as pages under that.
> I believe after a point the slide decks will be a goto pitch and most
> collaboration will occur on the wiki/hackpad.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/39#issuecomment-32115295
> .

## 

Kevin Curry
Advisor, Civic Hacker
Code for America
http://brigade.codeforamerica.org

Let's CodeAcross together this February 21-23:
http://www.codeforamerica.org/codeacross

**Comment by qwo** [comment]
So slidedeck? I imagine those are really hard to grasp without fully explaining it.

I would suggest maybe linking it to a city or place with a type of that app deployed.

IE click on "open budget visualization" -> Dialog: "it looks a little like this -> Redirects to openoaklandbudget.org

**Comment by bschoenfeld** [comment]
At the last hack night, we decided to us Github markdown files to do this. Those have been created and linked to. They could still use some fleshing out but I'll go ahead and close this.
