### ISSUE TITLE
create seperate page for projects

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/previous-landing#4]
our projects are getting out of control (awesome) and it would be great to have a page showing details on each one, with team members, status updates, etc.  Maybe another web tool would be better for this, or maybe just static html for now. http://codeforphilly.org/projects has a good example.

**Comment by bschoenfeld** [comment]
:thumbsup:

**Comment by milafrerichs** [comment]
Implemented a first iteration: http://milafrerichs.github.io/c4hrva-landing/#projects
I thought since the page is a one-pager a simple hidden details-"page" would be nice.
maybe the stats should be aggregated via the github-api

**Comment by qwo** [comment]
closed on the great issue purge of June/2014.

Sorry, Reopen if this is not solved in issue #103
