### ISSUE TITLE
Code Across: sponsor section 

### ISSUE THREAD

**Issue by wbprice** [Code4HR/previous-landing#49]
Give hierarchy to donors section:
1. CfA, DE, TCC
2. Local companies (xTuple, InMotion Hosting)
3. National companies.

**Comment by wbprice** [comment]
http://imgur.com/APovMu7 desktop >=960px
http://imgur.com/uqtv18L tablet  >= 768px
http://imgur.com/pJEK9RD mobile

**Comment by kmcurry** [comment]
Add xTuple under 2. local cos.

**Comment by BretFisher** [comment]
use this one https://www.xtuple.com/sites/default/files/images/xtuple_worlds-number1-opensource-erp_logo.png

**Comment by BretFisher** [comment]
maybe bump down hatch to 2nd row, would really like xtuple to be first row. Thanks.

**Comment by wbprice** [comment]
This is going to be included in another feature's pull request.

**Comment by wbprice** [comment]
http://imgur.com/N2pFSFR,VtMAy6X,mQ2Sgno 

Keeping all the first tier sponsors on one row is going to be difficult to handle on mobile.  We can do something else to mark off levels of contribution if logo size alone won't cut it.

**Comment by qwo** [comment]
cfa wouldn't mind if we bumped the brigade logo maybe? I mean i'm sure this isn't the last tier 1 sponsor :)

**Comment by wbprice** [comment]
Right, we should expect to see more sponsors.  I'll retool this section and stop worrying about getting everything on one row.

**Comment by jalbertbowden** [comment]
it would flow if they were 1 to a row. i think maybe size tweak too.
increase. for non-desktop.
more min.
haven't viewed source but should just be some media queries.
worth a gander? lmk. ill play when i get home.

On Friday, January 24, 2014, William Blaine Price notifications@github.com
wrote:

> Right, we should expect to see more sponsors. I'll retool this section and
> stop worrying about getting everything on one row.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/49#issuecomment-33260332
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by wbprice** [comment]
Obviously I'm biased, but at what level should I put InMotion?  Logos we can use are in issue #59.

**Comment by kmcurry** [comment]
It's going to get crowded! :smile: How about CfA, DE & TCC up top. Second row is xTuple & InMotion (and anyone else who comes in at similar level). Third is Hatch, HackVA & Maker. Bottom is Microsoft & ESRI. That's a fair approximation of both financial commitment and effort, i.e., TCC, Dominion and we are all committing funds, space and labor. Keep in mind that donors for mixers and meals get their own signs for that, too.

**Comment by kmcurry** [comment]
The sizes need to be adjusted. It may be more efficient to use a master image from the design team. There are three that are disproportionately too large, especially since one does not appear on our donor sheet and one has not yet committed. The bottom two images should be replaced with the graphics CfA sent us. I'm on IRC to be more specific.

**Comment by kmcurry** [comment]
Fixed with c4a937792a6b84a0aa298630b550cf8ba2b02db3
