### ISSUE TITLE
HRT Bus Finder demo link is broken

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/previous-landing#5]
It points to http://bus.codeforvirginiabeach.org/busfinder/

Should point to http://bus.codeforhamptonroads.org/

**Comment by wbprice** [comment]
And now, hrtb.us

**Comment by bschoenfeld** [comment]
Are you sure? I just went to codeforhamptonroads.org and clicked on the
link. It worked fine.

**Comment by wbprice** [comment]
My bad, it is pointed correctly.  I'll open a pull request for demo -> live later.
