### ISSUE TITLE
Code Across: Optimize images, minify css, etc.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/previous-landing#51]
Set up Grunt and optimization tasks.

**Comment by BretFisher** [comment]
1. Right now we'd save nearly 200K in every page load by just resizing or optimizing images. You can use Google Chrome Pagespeed Insights and it'll tell you what the current  size is and what it should be.

**Comment by jalbertbowden** [comment]
kraken.io will shrink them. if thats not good enough make a sprite.

On Sunday, February 16, 2014, Bret Fisher notifications@github.com wrote:

> 1. Right now we'd save nearly 200K in every page load by just resizing
>    or optimizing images. You can use Google Chrome Pagespeed Insights and
>    it'll tell you what the current size is and what it should be.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/51#issuecomment-35208663
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by kmcurry** [comment]
This is not an issue compared to other things, i.e., there is not any problem. The donor logos are all the wrong sizes. That needs to be fixed first.

**Comment by BretFisher** [comment]
kraken will shrink file size, but not resize image, which is the issue for most of them.
