### ISSUE TITLE
Add anchors for major sections

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/previous-landing#53]
Put <a> tags into the page so that we can do things like:

http://codeforhamptonroads.org/codeacross/#challenges

**Comment by wbprice** [comment]
All the sections already have ids, so this works already.

**Comment by qwo** [comment]
its just lacking a visible navigation bar or clickable area for the section. 

Is this a request for a NavBar?

**Comment by wbprice** [comment]
I'm down for making a navbar.

**Comment by kmcurry** [comment]
My mistake!
