### ISSUE TITLE
Create a section for invited guests

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/previous-landing#62]
Add a section to the event page for invited guests.

Add photos I sent to c4hrva-team@

Caption photos as follows. Link names to LinkedIn profiles.

Sheila Dugan: Digital Inclusion
Manager at EveryoneOn, Code for America Fellow. Virginia Governor's Fellow.

Waldo Jacquith: Open Data 
Director of the US Open Data Institute. White House Champion of Change. Virginian. 

More to follow.

**Comment by wbprice** [comment]
The order is:
-Sheila Dugan
-Waldo Jacquith
-Andreas Addison
-Ben Berkowitz  (not yet confirmed)

**Comment by kmcurry** [comment]
![s dugan - pic](https://f.cloud.github.com/assets/69151/2036387/ba71a85e-894a-11e3-896b-c2165c075b00.png)
![jaquith](https://f.cloud.github.com/assets/69151/2036388/bd0e06c0-894a-11e3-9376-830bb666aac2.jpg)

**Comment by bschoenfeld** [comment]
New sponsors! They are one in the same.

![devlicio us](https://f.cloud.github.com/assets/565347/2094379/29ef6be6-8ecb-11e3-94ab-00b577d529dd.png)
![codebetter com](https://f.cloud.github.com/assets/565347/2094380/29efa8d6-8ecb-11e3-871c-b20804708734.png)
