### ISSUE TITLE
Mention Prizes and Raffels on CA page

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/previous-landing#73]
mention there will be dozens of SWAG items, Raffles and Prizes including Nexus 7 tablets, 1Yr Inmotion Hosting, and more.

**Comment by wbprice** [comment]
Have we decided how we want to award these?  For the big ticket items, are we planning on having competition/judges and all that?

**Comment by kmcurry** [comment]
Have not yet decided. Let's discuss it this evening and/or Wed.

Check out the Donations & Sponsors spreadsheet for what we have.

On Sun, Feb 16, 2014 at 10:53 AM, William Blaine Price <
notifications@github.com> wrote:

> Have we decided how we want to award these? For the big ticket items, are
> we planning on having competition/judges and all that?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/73#issuecomment-35199974
> .

## 

Kevin Curry
757-613-8158
Advisor, Code for America
http://brigade.codeforamerica.org

CodeAcross HRVA February 21 & 22:
http://www.codeforhamptonroads.org/codeacross

**Comment by qwo** [comment]
I suggest we do it asap in terms of, offering it as a sign up or door prize
or prize pool is more advantgeous  earlier than later

I wont be able to join on tonight because ill be flying but best regards

On Sun, Feb 16, 2014 at 12:14 PM, Kevin Curry notifications@github.comwrote:

> Have not yet decided. Let's discuss it this evening and/or Wed.
> 
> Check out the Donations & Sponsors spreadsheet for what we have.
> 
> On Sun, Feb 16, 2014 at 10:53 AM, William Blaine Price <
> notifications@github.com> wrote:
> 
> > Have we decided how we want to award these? For the big ticket items, are
> > we planning on having competition/judges and all that?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/c4hrva/c4hrva-landing/issues/73#issuecomment-35199974>
> > .
> 
> ## 
> 
> Kevin Curry
> 757-613-8158
> Advisor, Code for America
> http://brigade.codeforamerica.org
> 
> CodeAcross HRVA February 21 & 22:
> http://www.codeforhamptonroads.org/codeacross
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/73#issuecomment-35202214
> .
> 
> ---
> 
> NOTE: This message was trained as non-spam. If this is wrong, please
> correct the training as soon as possible.
> Spamhttps://www.spamtrap.odu.edu/canit/b.php?i=03Lr5eLnv&m=33c9f1524c46&t=20140216&c=s
> Not spamhttps://www.spamtrap.odu.edu/canit/b.php?i=03Lr5eLnv&m=33c9f1524c46&t=20140216&c=n
> Forget previous votehttps://www.spamtrap.odu.edu/canit/b.php?i=03Lr5eLnv&m=33c9f1524c46&t=20140216&c=f

## 

Stanley Zheng
B.S. Comp Sci ODU '14
Cell: (347)-399-3732
@stanzheng

**Comment by qwo** [comment]
solved in the past.
