### ISSUE TITLE
Add open data activities from CfA CodeAcross page to our event page and prioritize

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/previous-landing#75]
CfA has three well defined and structured activities around open data that we should feature on our event page(s) and at the event itself. If feasible, i.e., doesn't make a tl;dr mess, add these to our page and feature them at the tops of the Challenges and Activities sections. (Maybe also reshuffle the others, too, to share time at the top.) List the Open Data Inventory and Open Civic Data Scraper as Activities and the Open Data Policy as a Challenge.

http://www.codeforamerica.org/codeacross-2014/#resources

**Comment by wbprice** [comment]
addressed in #78.
