### ISSUE TITLE
Add Grow, uDig, and Modis to Sponsors

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/previous-landing#76]
Grow and uDig are committed, Modis is in final discussions, so we'll assume it's a go.

udig: http://www.hrssug.org/SiteAssets/UDig%20Logo.jpg

Grow: https://drive.google.com/file/d/0B_WC8QOgiwjzc3RSTTNLZVVIN29fV3JVSDNtRnR0SHY2VW4w/edit?usp=sharing

Modis: http://aitprich.org/wp-content/uploads/2012/11/NEW-Modis-Logo.jpg

**Comment by wbprice** [comment]
addressed in #77
