### ISSUE TITLE
Encourage non-coders to participate

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/previous-landing#8]
Our brigade has gotten about 300% better since our designers joined. I don't think we could ever have enough of them. We could also use some internet savy volunteers who don't know anything about coding or graphic design but can edit hrva wiki, test out the bus app, or trade ideas for beer at meetups. I don't think our landing page gets that message across.

**Comment by bschoenfeld** [comment]
Hey @kmcurry, how does CFA handle this problem? Maybe the brigade should have been called Internet For America. Internet can be a verb, right?

**Comment by kmcurry** [comment]
We haven't really had to deal with this at CfA. From the beginning we've
had, for example, more designers following us and applying for fellowships
than coders. That said, we have been even more proactive in making
designers feel included & welcome. Hiring Angel as Designer in Residence &
Cyd Harrell as UX Evangelist are two examples.

I agree we should do more to be inclusive in our appeal on the site.

On Fri, Mar 15, 2013 at 2:56 PM, Ben Schoenfeld notifications@github.comwrote:

> Hey @kmcurry https://github.com/kmcurry, how does CFA handle this
> problem? Maybe the brigade should have been called Internet For America.
> Internet can be a verb, right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/c4hrva-landing/issues/8#issuecomment-14978725
> .

## 

Kevin Curry
Program Director
CfA Brigade
757.613.8158
GMT-5
http://brigade.codeforamerica.org

**Comment by jalbertbowden** [comment]
maybe we could put something together like this http://www.brainpickings.org/index.php/2013/03/11/how-our-government-helps-us/

**Comment by qwo** [comment]
closed on the great issue consolidation of June/2014.

Sorry, Reopen if this is not solved in issue #103
