### ISSUE TITLE
Add Intro to GitHub presentation to resources menu.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/previous-landing#83]
https://docs.google.com/presentation/d/1i4RpQGU0xO2jXTqzsekmWyjOJzw6C0sCPkCC4GCr-AY/edit?usp=sharing

**Comment by qwo** [comment]
that would be sick if there was a PPT to Reveal.JS converter. 
http://lab.hakim.se/reveal-js/#/

Im going to stash this in our google drive docs and file it under "resources"
